name: CI/CD Pipeline for Vite React App

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: cd WebUI/board-booker && npm install
      - name: Build the application
        run: cd WebUI/board-booker && npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: cd WebUI/board-booker && npm test
      - name: Lint code
        run: cd WebUI/board-booker && npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: cd WebUI/board-booker && npm install
      - name: Deploy to GitHub Pages
        run: |
          npm install gh-pages --save-dev
          gh-pages -d build
