name: CI/CD Pipeline for Vite React App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - name: Build the application
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - name: Run unit tests
        run: npm test
      - name: Code quality analysis
        run: eslint .

      - name: Send email notification
        if: ${{ job.status == 'success' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server: smtp.gmail.com
          from: h4z3y.bc+gha@gmail.com
          to: h4z3y.bc@gmail.com
          subject: Build Successful!
          body: Your build has completed successfully.
