name: CI/CD Pipeline for Vite React App

on:
  push:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Navigate to project directory
        working-directory: WebUI/board-booker/
        run: cd WebUI/board-booker/ && npm install

      - name: Build the application
        working-directory: WebUI/board-booker/
        run: cd WebUI/board-booker/ && npm run build

      - name: Run unit tests
        working-directory: WebUI/board-booker/
        run: cd WebUI/board-booker/ && npm test

      - name: Lint code
        working-directory: WebUI/board-booker/
        run: cd WebUI/board-booker/ && npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: WebUI/board-booker/
        run: cd WebUI/board-booker/ && npm install

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: WebUI/board-booker/build

  notify:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Build ${{ job.status }}!
          body: Your build has ${{ job.status }}. Check the workflow run for more details.
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
